### ISSUE TITLE
[BUG] MQTT controls not working anymore

### ISSUE THREAD

**Issue by jaynis** [joshuar/go-hass-agent#101]
Hi. After updating to **v7.0.0** the agent does not connect to the MQTT broker anymore from my system, resulting in all MQTT controls such as screenlock not working anymore. In the course of this major update I deleted the entire configuration folder and started over again from scratch. But apparently the `mqtt.enabled` setting in the newly created `preferences.toml` file is ignored.

I tracked down the issue to the following line, which seems to always return an empty default configuration:
https://github.com/joshuar/go-hass-agent/blob/72213853854c64a370f0d7bb5c45a8872503adf1/internal/agent/runners.go#L171
When I replace this line with a simple `prefs, err := preferences.Load()` the preferences are retrieved properly and MQTT works again. But I assume `FetchFromContext` is used here for some reason. Can you elaborate how those context based preferences are supposed to work and what their advantage is over simply loading them? If I understand it correctly `EmbedInContext` stores the preferences in the context and `FetchFromContext` can be used to retrieve them aftewards. However, I can only find a single occurrence of `EmbedInContext` in the entire project (apart from the tests) and this is in some UI package.

**Comment by joshuar** [comment]
Hey @jaynis, oh dear! I'm sorry the new version didn't work correctly and you had to edit the code and re-register to get it working, that's not what was intended!

I can see the problem. I had changed what values were stored in the context from the all preferences to just the API URL and an HTTP client. Of course, this means all the MQTT preferences are missing, so MQTT control won't work. 

What you have done is a good fix, thank you for your code sleuthing! I'll implement that in a patch release (7.0.1) ASAP.

For more background, indeed I've been exploring whether to continue embedding preferences in the context passed to those runners or just load it from file when needed with the load function. Advantage of the context is the preferences will stay consistent for the lifetime of the agent run. Loading gives an advantage of potentially being able to reload preferences in the future and dynamically change how the agent runs. So the code may change in the future, but I will look at adding more tests to try to catch problems like this (the amount of test code in general is on my mind constantly).

Thank you again for first reporting this, finding a good fix and for using the agent!
