### ISSUE TITLE
[FEATURE REQUEST] Audio control

### ISSUE THREAD

**Issue by joshuar** [joshuar/go-hass-agent#122]
**Describe the solution you'd like**
The ability to control the volume of the current/default audio device. Volume up/down and toggle mute.

**Describe alternatives you've considered**
No other alternatives AFAIK.

**Additional context**
Unsure where to source these controls on Linux at least. Likely will need to resort to command-line utilities.

**Comment by joshuar** [comment]
Volume control is now available as of v9.0.0 when MQTT is enabled.

**Comment by howels** [comment]
Can we select the audio output device? I was considering a d-bus or script command but this really needs a drop-down selector instead a number or binary switch.
