### ISSUE TITLE
Unsupported or unknown portal. App sensors will not run.

### ISSUE THREAD

**Issue by janusbenissa** [joshuar/go-hass-agent#126]
On Linux mint I got the following warning:
Unsupported or unknown portal. App sensors will not run.

Is Mint not supported?

**Comment by joshuar** [comment]
Hmm, for the app sensors, it isn't so much the distribution but the desktop environment that matters. Which desktop environment are you using? 

Side-note, I might need to adjust the log message, the "portal" it is referring to is the [XDG Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/docs/index.html) and maybe that isn't something users need to worry about as their desktop environment handles it.

**Comment by janusbenissa** [comment]
I'm working with Linux Mint 21.3 XFCE
The sensors are indeed working but I have to start go-hass-agent  in the therminal, otherwise it is not starting.
Thanks for your quick response.

**Comment by joshuar** [comment]
I looked into this a bit further. I fired up a VM with Linux Mint running Xfce. Unfortunately, it doesn't look like it has the necessary D-Bus functionality (the `org.freedesktop.impl.portal.Background` interface and methods) that are used to get the current app and number of running apps  🙁 That means the agent won't be able to report which desktop app is currently being used and how many other desktop apps are running.

I will fix the warning message, the current one doesn't need to be exposed by default, I'll add a more descriptive one.

I also noted that yes indeed, you don't have a menu entry for the agent on Xfce. I will look to fix this as well so you don't have to launch it from the terminal.

**Comment by janusbenissa** [comment]
Great news, thanks.

**Comment by joshuar** [comment]
Just following up, [v7.3.1](https://github.com/joshuar/go-hass-agent/releases/tag/v7.3.1) has an improved warning message and should have a menu item on Xfce. 

I'll close this issue off for now as I think we've worked through the problems here, but please re-open if not.

Thanks for trying out the agent!
