### ISSUE TITLE
[BUG] Panic caused by sending on closed channel

### ISSUE THREAD

**Issue by jaynis** [joshuar/go-hass-agent#128]
Hi. From time to time my `go-hass-agent` crashes with a panic caused by sending on an already closed channel in the `networkConnection.go`:
```go
panic: send on closed channel

goroutine 451368 [running]:
github.com/joshuar/go-hass-agent/internal/linux/net.(*connection).monitorAddresses.func2.1()
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/net/networkConnection.go:171 +0x1af
created by github.com/joshuar/go-hass-agent/internal/linux/net.(*connection).monitorAddresses.func2 in goroutine 296569
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/net/networkConnection.go:163 +0x17a
exit status 2
```

I can reproduce this issue by manually connecting/disconnecting to/from my WiFi. However, it does not happen every time but only at maybe every 10th attempt. Therefore I assume this might be some kind of race condition.

**Comment by joshuar** [comment]
Yeah, the network sensor code is complicated and I always have in the back of my mind to refactor it a bit. It's already been refactored at least once 😝 

I think if you are getting crashes, that means I need to look into that refactor sooner than later. I'll revisit the code and see if I can't improve it to reduce the chance of any race conditions.

**Comment by joshuar** [comment]
Hey @jaynis, with release [v8.0.0](https://github.com/joshuar/go-hass-agent/releases/tag/v8.0.0), the network connection sensor code has been reworked. It no longer shares channels for various tracking code which makes the likelihood of the above error much less. I've also checked with built-in go race detection tool and there are no longer any race conditions in the network connection sensor code. In my manual testing of constantly toggling my wifi on/off, I could not get the agent to crash. 

I'm hoping this version fixes this issue for you as well. I'm going to preemptively close this issue on that assumption, but please test and report/re-open if necessary.
