### ISSUE TITLE
[BUG] Network offline state not correctly reported to HA

### ISSUE THREAD

**Issue by jaynis** [joshuar/go-hass-agent#129]
Hi. Apparently the _Offline_ state of an network interface is not correctly reported to HA. In the event of an network interface disconnection the state either stays at _Online_ or at _Deactivating_ (depending on the type of the interface). I think the reason is that the following switch-case statement just closes the channel in case of _Offline_ but does not send the state before:
https://github.com/joshuar/go-hass-agent/blob/a95b6a7f48045922bbf7f9ae0871dc251dd208e0/internal/linux/net/networkConnection.go#L105-L113

**Comment by joshuar** [comment]
Fixed with d6ffeb193bf5dd2eef6e6d4f0c61508a948841c3!
