### ISSUE TITLE
[BUG] go-hass-agent does not creat state folder for log file, crashes therefore on fresh install.

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#136]
**Go Hass Agent Version**
7.3.1

**Describe the bug**
On a fresh install and if the state folder is not existing, the ~/.local/state/go-hass-agent.log log file is not created and go-hass-agent crashes.
 
**To Reproduce**
Steps to reproduce the behaviour:
1. (Delete the log file if existing)
2. (Delete or rename state folder if existing)
3. Start go-hass-agent

**Expected behaviour**
I would expect go-hass-agent to create the state folder if not existing.

**Logs**
```
9:41AM ERR Unable to open log file for writing. error="open ~/.local/state/go-hass-agent.log: no such file or directory"
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Arch Linux
 - Version 6.8.5-arch1-1

**Comment by joshuar** [comment]
That log file error should be non-fatal. In my testing, the agent continues with displaying the registration window and running.

Could you try running the agent in a terminal with debug logging `go-hass-agent --debug` and see if there is any more output or a stack trace produced?
