### ISSUE TITLE
[BUG] v7.3.1 script not working 

### ISSUE THREAD

**Issue by Erreur32** [joshuar/go-hass-agent#140]
**Go Hass Agent Version**
v7.3.1

**Describe the bug**
 Maybe it's not a bug, i could miss something ?
 
My go-hass-agent starting well, no crash ,   but my script still not working, i have starting with --debug and i see :

`RN Cannot run script error="could not unmarshal script output" script=/home/debian32/.config/com.github.joshuar.go-hass-agent/scripts/check_version_ha_agent_json.sh `

the script have a good right, and the output is :

 `{
  "schedule": "@every 1h",
  "sensors": [
    {
      "sensor_name": "go hass agent version_installed",
      "sensor_icon": "mdi:package",
      "sensor_state": "7.3.1"
    }
  ]
}
`

I would check the current go-hass-agent vesion installed  to automate  warning when new version.

 and don't see any new sensor. 

Thanks for this great tool ;)

**Comment by joshuar** [comment]
Hey @Erreur32 that's super odd. I just tested on my machine by creating a script that simply echos that JSON output, and the agent accepts it and generates a sensor.

The "could not unmarshal script output" means the agent couldn't parse the output as either JSON, TOML or YAML (i.e., it doesn't recognise the output). Maybe the script is outputting some strange/unexpected whitespace?

You can use [dasel](https://github.com/TomWright/dasel) to [validate](https://daseldocs.tomwright.me/v/v1/usage/validate) the JSON output of the script. Once you have dasel installed, a command like:

```shell
/home/debian32/.config/com.github.joshuar.go-hass-agent/scripts/check_version_ha_agent_json.sh > /tmp/script.output.json && dasel validate /tmp/script.output.json && rm /tmp/script.output.json
```

Should print out `pass /tmp/script.output.json` or a `fail (some error)...` if it failed to validate.

If it is possible, can you share the script and I can see if I can reproduce with the actual script?

**Comment by Erreur32** [comment]
Good point for validiting the json,  first time i need do that.

```
dasel validate .config/com.github.joshuar.go-hass-agent/version_installed.json
fail .config/com.github.joshuar.go-hass-agent/version_installed.json could not unmarshal data: could not decode object: invalid character '\x1b' in string literal
Error: 1 files failed validation
```
And apparently, the go-hass-agent version command  also returns this ANSI control sequence along with the actual version. 
--> "v7.3.1[0m" 

So I filtered it and now it seems to work :)
sed 's/\x1B\[[0-9;]*[a-zA-Z]//g'


my working script (for example propose):
```
generate_json_output() {
    script_name="go hass agent version_installed"
    script_version=$(sudo -u debian32 /home/debian32/.local/bin/go-hass-agent version | grep -oP '(?<=go-hass-agent: ).*' | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g')

    # Creation JSON file (creating a file , in case of)
    cat <<EOF > /home/debian32/.config/com.github.joshuar.go-hass-agent/version_installed.json
{
  "schedule": "@every 1h",
  "sensors": [
    {
      "sensor_name": "$script_name",
      "sensor_icon": "mdi:package",
      "sensor_state": "$script_version"
    }
  ]
}
EOF
}

generate_json_output

cat /home/debian32/.config/com.github.joshuar.go-hass-agent/version_installed.json
```

Question:  On launch, the script doesn't seem to update, so you have to wait until the next **calendar** to get an update, is that correct?

**Comment by joshuar** [comment]
I'm glad it's now working! Yes, the output of the version command has some escape sequences to colour the output:

![image](https://github.com/joshuar/go-hass-agent/assets/7401/42ae5b40-008a-499f-9280-c43c12a4d3b9)

As an alternative to your script, I could add a sensor that shows the agent version that only updates whenever the agent is started?

Hmm, I think you can only remove a sensor if it is no longer provided by whatever was sending it. Otherwise you could just hide it. You can follow the instructions for [customising entities](https://www.home-assistant.io/docs/configuration/customizing-devices/):

    Select the entity, either from the frontend or by selecting the info button next to the entity in the Developer Tools “States” tab.
    Select the cog icon in the right corner of the entity’s dialog.
    Toggle the "Enabled", "Visible" switches, or click "DELETE" depending on your preference.

**Comment by Erreur32** [comment]
>  As an alternative to your script, I could add a sensor that shows the agent version that only updates whenever the agent is started?

As there is no automatic update, this seems like a good idea to me.
 
i have made a card and script to check online version on Github also:
![Firefox_Screenshot_2024-04-23T07-35-46 722Z](https://github.com/joshuar/go-hass-agent/assets/2248137/1964a400-8607-4e07-9d3b-25ac933258a1)
