### ISSUE TITLE
[BUG] v8.0.0  don't have any .tar.xz  release for Debian.

### ISSUE THREAD

**Issue by Erreur32** [joshuar/go-hass-agent#144]
in the new update v8.0.0 i don't see any .tar.xz  release for Debian.

**Comment by joshuar** [comment]
Hey @Erreur32 I've updated the release and the tar.xz for Debian is now available.

- [](https://github.com/joshuar/go-hass-agent/releases/download/v8.0.0/go-hass-agent.tar.xz)
- [](https://github.com/joshuar/go-hass-agent/releases/download/v8.0.0/go-hass-agent.tar.xz.sig)

Heads up I will need to rename these for the next release to distinguish between x86, arm and arm64 builds. Likely the file will just have the arch in the name.

**Comment by hafkensite** [comment]
This did break the arch user repository package, as it noticed the files have changed since the initial release:
```
==> Making package: go-hass-agent-bin 8.0.0-1 (Mon 29 Apr 2024 01:11:17 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found go-hass-agent-8.0.0.pkg.tar.zst
==> Validating source files with sha256sums...
    go-hass-agent-8.0.0.pkg.tar.zst ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: go-hass-agent-bin-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
 ```
 
 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=go-hass-agent-bin

**Comment by joshuar** [comment]
Oh wow, I didn't know someone had packaged it up in AUR. Neat! Though I'm not familiar with packaging for arch (I'm using a tool, [nfpm](https://nfpm.goreleaser.com/), which handles it for me). 

If there is something I can do to make it easier to package, please let me know!

**Comment by joshuar** [comment]
This should be fixed now for future releases, there was a single character breaking the build pipeline.
