### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#151]
**Go Hass Agent Version**
8.0.0

**Describe the bug**
My four go-hass-agents running as systemd services in terminal mode stop reporting data after I log out. For my raspberry pis this happens after about 3 minutes, for one Server around half an hour and another server around 5 minutes after logout. From the log, I suppose it is because the logout is interpreted as `Crtl+C`. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start go-hass-agent as systemd service
2. logout from pc
3. watch sensor in HA stop getting data

**Expected behaviour**
I would assume that go-hass-agent would continue running.

**Screenshots**
Raspberry Pi
![raspi](https://github.com/joshuar/go-hass-agent/assets/32816598/c1b43732-0033-4e25-8fc7-d8ef44a86c0b)

Server 1
![server1](https://github.com/joshuar/go-hass-agent/assets/32816598/d87b9f78-df36-4012-88c0-c7c8d40475d4)

Server 2
![server2](https://github.com/joshuar/go-hass-agent/assets/32816598/2016929d-9a76-4f7b-a311-6050a9186779)

**Logs**
I logged out at 8:55 and around 10:47. After the logout at 8:55 there is nothing reported until next loging at 10:44 and the `Ctrl+C` is mentioned :
```
…
{"level":"debug","name":"Bytes Received Throughput","id":"bytes_received_throughput","state":1196618,"units":"B/s","time":"2024-04-30T08:55:26+02:00","message":"Sensor updated."}
{"level":"debug","name":"Bytes Received","id":"bytes_received","state":129359045801,"units":"B","time":"2024-04-30T08:55:26+02:00","message":"Sensor updated."}
{"level":"debug","name":"Bytes Sent","id":"bytes_sent","state":99104703901,"units":"B","time":"2024-04-30T08:55:26+02:00","message":"Sensor updated."}
{"level":"debug","name":"Bytes Sent Throughput","id":"bytes_sent_throughput","state":1771136,"units":"B/s","time":"2024-04-30T08:55:26+02:00","message":"Sensor updated."}
{"level":"debug","name":"CPU Usage","id":"cpu_usage","state":7.73176146370674,"units":"%","time":"2024-04-30T08:55:27+02:00","message":"Sensor updated."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Ctrl-C pressed."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Agent done."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped power state sensor."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped problems sensor."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped load average sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopping cron scheduler for script sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped CPU usage sensor."}
{"level":"error","error":"read unix @->/run/dbus/system_bus_socket: use of closed network connection","time":"2024-04-30T08:55:27+02:00","message":"Could not set up a geoclue client."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped disk IO sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped disk usage sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped memory usage sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped time sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped temp sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped network stats sensors."}
{"level":"debug","time":"2024-04-30T08:55:27+02:00","message":"Stopped users sensors."}
{"level":"debug","time":"2024-04-30T10:44:32+02:00","message":"Read sensor registry from disk."}
{"level":"debug","time":"2024-04-30T10:44:32+02:00","message":"Agent already registered."}
{"level":"debug","time":"2024-04-30T10:44:32+02:00","message":"Starting worker funcs."}
{"level":"warn","error":"The name org.freedesktop.UPower was not provided by any .service files","time":"2024-04-30T10:44:32+02:00","message":"Could not retrieve battery list."}
{"level":"warn","time":"2024-04-30T10:44:32+02:00","message":"Unable to monitor for active applications. No app tracking available."}
{"level":"debug","error":"The name org.freedesktop.NetworkManager was not provided by any .service files","time":"2024-04-30T10:44:32+02:00","message":"Unable to retrieve property
…
```

[go-hass-agent.log](https://github.com/joshuar/go-hass-agent/files/15176442/go-hass-agent.log)

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Proxmox, Arch Linux and Arch Linux Arm
 - Version 6.8.4-2-pve, 6.8.7-arch1-1, 6.6.28-2-rpi

**Comment by joshuar** [comment]
Hmm, does your user have "lingering" enabled? What does `loginctl list-users` say? If it doesn't say yes, enable lingering with `loginctl enable-linger`.  As long as you have lingering enabled, your services should stay running after you close your last session on the machine.

**Comment by dflvunoooooo** [comment]
Great, thank you very much! It was indeed disabled on every system! I enabled it and it seems to be working. Even the raspberry pis  do report data after a reboot without the need to login first. Thank you very much again!
