### ISSUE TITLE
[BUG] v9.0.0 release is missing debian x86 .deb files

### ISSUE THREAD

**Issue by fhp** [joshuar/go-hass-agent#157]
**Describe the bug**
The [latest v9.0.0 release](https://github.com/joshuar/go-hass-agent/releases/tag/v9.0.0) is missing the Debian x86_64 / amd64 `.deb` file. Could you add these as well?

Maybe related to #144?

**Comment by joshuar** [comment]
Hey sorry about that! They are on the release page now. A single character broke my build pipeline, so I had to generate the packages manually :sob: I must have missed those!

**Comment by fhp** [comment]
Thanks! Just installed and working great :smile:
