### ISSUE TITLE
[BUG] VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#2]
**Describe the bug**
The application doesn't start properly. If started from gui, the hass icon bounces a moment and then nothing happens. If started from terminal `VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)` error appears and the program runs forever. 

**To Reproduce**
1. Download go-hass-agent-0.0.2-1-x86_64.pkg.tar.zst 
2. Install with 'sudo pacman -U go-hass-agent-0.0.2-1-x86_64.pkg.tar.zst '
3. Open Terminal and start 'go-hass-agent'

**Expected behavior**
I expected the application to start normaly.

**Logs**
A log will be very helpful to look into this bug report. To get the log:

1. Run `go-hass-agent` from a terminal or command-line with the `--debug` flag:
```[brian@arch-brian aa2]$ go-hass-agent --debug
3:52PM DBG Debug logging enabled.
3:52PM INF Starting agent.
3:52PM DBG /home/joshua/git/go-hass-agent/internal/agent/config.go:74 > Setting language to [de].
3:52PM DBG /home/joshua/git/go-hass-agent/internal/config/config.go:94 > Config seems invalid.
3:52PM WRN No suitable existing config found! Starting new registration process
3:52PM INF Looking for Home Assistant instances on the network...
3:52PM DBG /home/joshua/git/go-hass-agent/internal/agent/register.go:52 > Found a record 192.168.0.15:8123
2023/04/12 15:52:27 Fyne error:  window creation error
2023/04/12 15:52:27   Cause: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
2023/04/12 15:52:27   At: /home/joshua/gocode/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_notwindows.go:9
```

**Desktop (please complete the following information):**
 - OS: Arch-Linux 

Thank you in advance for your trouble.

**Comment by joshuar** [comment]
Hey @dflvunoooooo thanks for trying out go-hass-agent. I'm unsure what could be the cause of this error, except maybe a problem with the fyne UI toolkit I use on your system.

Does the fyne_demo app run for you (see instructions for installing [here](https://github.com/fyne-io/fyne#widget-demo))?

Is your system up to date with drivers and packages? Does this happen after you reboot?

**Comment by dflvunoooooo** [comment]
Thank you for your quick answer. It was indeed something with my nvidia graphics driver. I had problems with that yesterday. I reinstalled the drivers, rebooted and it is working. Thanks a lot.
