### ISSUE TITLE
[SENSOR] CPU Frequency

### ISSUE THREAD

**Issue by fdw** [joshuar/go-hass-agent#222]
**What are the sensors you would like to see in Go Hass Agent? What do they measure? Why are they useful? How would you use them in Home Assistant?**
I would like to track the CPU frequency in some way, to see how the CPU reacts to more or less load. Additionally, the current frequency governor might be nice.

**How do you access the sensor(s) currently?**
For example via `/proc/cpuinfo` (field `cpu MHz`). Governor is at `/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

**Comment by joshuar** [comment]
Hey thanks for this request. I have implemented CPU frequency sensors with 6b7b91fd0229bac4c5129e492e0359035e910f57 which will end up in the next release :tada:

**Comment by fdw** [comment]
Awesome, thank you!
