### ISSUE TITLE
[BUG] Tray Icon doesn't have proper naming

### ISSUE THREAD

**Issue by Potajito** [joshuar/go-hass-agent#229]
**Go Hass Agent Version**
v9.6.0

**Describe the bug**
The app name is not defined and it's using the AppID value from `prefs.go` `com.github.joshuar.go-hass-agent`

**To Reproduce**
Maybe this is a KDE thing, I know Gnome has another Tray behaviour. But repro steps on KDE are:
1. Install app
2. Click on tray icon
3. Observe the issue

**Expected behaviour**
A proper name for the app, something along the lines of "Go Hass Agent"

**Screenshots**

![image](https://github.com/user-attachments/assets/9eb82704-5e93-488d-bd15-044ee9f36f0b)

**Desktop (please complete the following information):**
Operating System: EndeavourOS 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.10.2-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7800X3D 8-Core Processor
Memory: 30,6 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Manufacturer: ASUS

**Comment by joshuar** [comment]
Hey thanks for reporting. I agree, the agent should use a better name. I've made commit 87d9ae4ba97a0e50c50b7a3a923fe610f201a6f9 which will make the agent display "Go Hass Agent". This will be in the next release.

Cheers!

**Comment by joshuar** [comment]
Hey there, since [v10](https://github.com/joshuar/go-hass-agent/releases/tag/v10.0.0) Go Hass Agent now displays a nicer tooltip. I'll close this issue off. Cheers!
