### ISSUE TITLE
[FEATURE REQUEST] Reduce log spam

### ISSUE THREAD

**Issue by fdw** [joshuar/go-hass-agent#236]
**Is your feature request related to a problem? Please describe.**
`go-hass-agent` writes to the syslog every time it can't update a sensor; which can be very often if the sensor is disabled. I'd like to reduce the size of the log.

**Describe the solution you'd like**
Can it, for example, only log the first time it can't update a sensor? Or at least a lot less often?

**Describe alternatives you've considered**
I could enable the sensor, but I don't need the data in HA, and I don't want to save it there.

**Comment by joshuar** [comment]
Hey thanks for reporting. I agree, that is excessive. In the current code, a major re-write of the logging code has happened and I can confirm the agent no longer spams the log about disabled sensors. So this will be a non-issue in the next release :tada:  

I'll leave this issue open until the release drops as a reminder.

**Comment by fdw** [comment]
While it is much better, I still get a regular log entry: `Errors fetching some chip/sensor values from hwmon API. worker=hwmon_sensors errors="some errors encountered while processing hwmon directory: some errors encountered while processing sensor files: could not read contents of file: read /sys/class/hwmon/hwmon1/of_node: is a directory"`

**Comment by joshuar** [comment]
Thanks for reporting this. I'm hoping [v10.1.1](https://github.com/joshuar/go-hass-agent/releases/tag/v10.1.1) has fixed this `hwmon` logging spam. Please keep the feedback coming if you feel there are log messages you don't find useful!

**Comment by fdw** [comment]
Looks a lot better now, thanks 🙂

I still get a regular mention of `WRN Unable to retrieve sensors. worker=abrt_problems_sensor worker_type=polling error="could not retrieve list of problems from D-Bus: error getting data: SystemBus: unable to get data org.freedesktop.problems.GetProblems from org.freedesktop.problems` 😉

**Comment by joshuar** [comment]
Good catch on this one @fdw! fecb599daf832d8b03ebce4410afd787d9502a40 should fix this in that the problems worker will check if problems can be fetch off D-Bus at start-up and then exit if it is not available, (i.e. not continue polling and failing). That's been added in [v10.2](https://github.com/joshuar/go-hass-agent/releases/tag/v10.2.0) :tada:

**Comment by joshuar** [comment]
Hey thanks again for reporting these. I think the log spam is a lot better now. I'll close this off, but please re-open if you think there are any further reductions that could be considered.

**Comment by fdw** [comment]
Yes, it's a lot better now. Thank you!
