### ISSUE TITLE
[BUG] No folder or file created on registration. Code 0 on first start. No preferences.toml.

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#267]
**Go Hass Agent Version**
Go Hass Agent: v10.1.1

**Describe the bug**
The registration works and shows up in HA, but the go-hass-agent folder is not created nor any files. If I then try to run go-hass-agent it fails with `FATAL Error checking registration status. error="device registration failed: could not register device: code 0: "`. After that, the go-hass-agent folder has been created, but only contains `agent.log` and `sensorRegistry/sensor.reg`. The first contains all errors shown on first run, the second is empty. 

Maybe related to #223?

**To Reproduce**
Steps to reproduce the behaviour:
0. (Delete all folders and stop the daemon if no clean install)
1. run `go-hass-agent register --force --terminal --server _URL_ --token _TOKEN_`
2. run `go-hass-agent --terminal run`
4. See error and empty folder

**Expected behaviour**
I would expect go-hass-agent to create the preference.toml file and start.

**Logs**
```
Sep  5 22:45:47.860 DEBUG Setting language. lang=[]
Sep  5 22:45:47.861 DEBUG Read sensor registry from disk. file=sensor.reg
Sep  5 22:45:47.867 FATAL Error checking registration status. error="device registration failed: could not register device: code 0: "
Sep  5 22:45:47.867 DEBUG Agent done.
Sep  5 22:45:47.868 WARN Could not connect to D-Bus. bus=SessionBus error="could not connect to bus: write unix @->/run/user/1000/bus: use of closed network connection"
…
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Arch Linux ARM
 - Version 6.6.34-2-rpi

**Comment by joshuar** [comment]
Hey @dflvunoooooo, that's an odd one. I unfortunately cannot reproduce in my arch test system, but it is amd64 not arm., but none of those messages hint that this could be an architecture issue.

Can you start again clean and run with debug logging enabled (add `--log-level debug` to the command-line)? That might give us more clues as to what might have happened. Please upload/attach the log to this issue (be sure to check and sanitize it for any private information).

**Comment by dflvunoooooo** [comment]
Hm, that is strange, sorry for that. I did a clean install (removed go-hass-agent and the .config/go-hass-agent folder). Installed go-hass-agent again and ran `go-hass-agent register --force --terminal --server http://IP:PORT --token _TOKEN_ --log-level debug` wich told me 
```
Sep 10 19:15:31.644 DEBUG Setting language. lang=[]
Sep 10 19:15:31.676 INFO Agent registered.
```
and the entity showed up under home assistant with one entity. Then I ran `go-hass-agent --terminal run --log-level debug` and got the same errors as bevore 
```
Sep 10 19:16:06.880 DEBUG Setting language. lang=[]
Sep 10 19:16:06.881 DEBUG Read sensor registry from disk. file=sensor.reg
Sep 10 19:16:06.887 FATAL Error checking registration status. error="device registration failed: could not register device: code 0: "
Sep 10 19:16:06.888 DEBUG Agent done.
Sep 10 19:16:06.888 WARN Could not connect to D-Bus. bus=SessionBus error="could not connect to bus: read unix @->/run/user/1000/bus: use of closed network connection"
Sep 10 19:16:06.889 WARN Could not connect to D-Bus. bus=SystemBus error="could not connect to bus: read unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.889 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor for active applications: no portal present"
Sep 10 19:16:06.889 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor for active applications: could not connect to bus: read unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.890 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor for desktop settings: no portal present"
Sep 10 19:16:06.890 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor location updates: unsupported hardware"
Sep 10 19:16:06.891 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor for network connections: could not connect to bus: read unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.891 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor laptop sensors: unsupported hardware"
Sep 10 19:16:06.891 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor power profile: could not connect to bus: read unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.892 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor power state: could not connect to bus: write unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.892 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor power state: could not connect to bus: read unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.892 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor abrt problems: could not connect to bus: write unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.893 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor power profile: could not connect to bus: read unix @->/run/dbus/system_bus_socket: use of closed network connection"
Sep 10 19:16:06.893 DEBUG Processing sensor updates.
Sep 10 19:16:06.894 DEBUG Stopping all sensor controllers.
Sep 10 19:16:06.894 DEBUG Stopping cron scheduler. controller=scripts
Sep 10 19:16:06.894 DEBUG Exiting script controller. controller=scripts
```
and with still one entity in Home Assistant.

**Comment by joshuar** [comment]
Hey @dflvunoooooo just following up to let you know I haven't forgotten about this issue and am still looking into ways to reproduce. I have not made progress there, but all the same, it's on my mind.

I would be curious if the latest 10.2.x version is any different?

**Comment by dflvunoooooo** [comment]
Thanks for reaching out to me again and for not forgetting about me. It is indeed working with 10.2.x as expected. I will close this issue.
