### ISSUE TITLE
[BUG] Power Off command not working after latest update

### ISSUE THREAD

**Issue by rouloy** [joshuar/go-hass-agent#277]
**Go Hass Agent Version**
v10.2.0

**Describe the bug**
Power Off not triggering a Shutdown

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh Install go-hass-agent
2. Link App to Home Assistant
3. Press Button Power Off
4. See error.

**Expected behaviour**
On button press the system should shutdown

**Screenshots**
Screenshot from Mqtt explorer showing message is coming from HA and is sent out
![grafik](https://github.com/user-attachments/assets/f71d0bfd-fa28-467d-bd8b-6b214cfd7e54)

**Logs**
A log will be very helpful to look into this bug report. To get the log:

Sep 13 17:25:38.187 WRN Could not start a sensor worker. linux.controller=sensor error="unable to monitor location updates: unsupported hardware"
Sep 13 17:25:38.187 WRN Could not start a sensor worker. linux.controller=sensor error="unable to monitor laptop sensors: unsupported hardware"
Sep 13 17:25:38.188 WRN Could not start a sensor worker. linux.controller=sensor error="unable to fetch ABRT problems from D-Bus: SystemBus: unable to get data org.freedesktop.problems.GetProblems from org.freedesktop.problems: The name is not activatable"
Sep 13 17:25:38.376 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.385 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.385 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.386 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.389 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.389 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.389 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.400 ERR Process sensor failed. error="%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"
Sep 13 17:25:38.400 ERR Process sensor failed. error="%!v(PANIC=Error

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution  Manjaro
 - Version Linux 6.9.12-3-MANJARO

**Additional context**
All other commands, like Mute/Unmute, Hibernate, Lock Session are working as intended

**Comment by joshuar** [comment]
hey @rouloy thanks for trying out Go Hass Agent and reporting the issue. I've fixed this with c44cd2cefb0c3367d896a72db205d61324d562de and released [v10.2.1](https://github.com/joshuar/go-hass-agent/releases/tag/v10.2.1) containing the fix. Please try it out and report back!

**Comment by rouloy** [comment]
HEY @joshuar  thanks for the time and work you put into it! Seems to work again :)

**Comment by joshuar** [comment]
Hey @rouloy that's great to hear, thanks for reporting back. I'll close this issue off.
