### ISSUE TITLE
[BUG] Unsupported or unknown portal. App sensors will not run.

### ISSUE THREAD

**Issue by Compukid** [joshuar/go-hass-agent#58]
**Describe the bug**
Not seeing sensors in HA, WRN in debug shows unknown portal is an issue.

**To Reproduce**
I'm running the terminal command...
go-hass-agent register --terminal --token _Token_ --server _URL_
*** where _Token_ and _URL_ are the actual token and URL for my home assistant***
[Output]
12:21AM WRN No UI. Will not display tray icon.
12:21AM WRN No UI. Likely running headless. Not running Fyne UI loop.
12:21AM INF Device registered with Home Assistant.

**Expected behavior**
I expect some sensors in home assistant, but nothing shows up. 

**Logs**
go-hass-agent  info
12:15AM INF Device Name Desktop2.Device ID 24d0d3ec-8c60-4939-a116-f7acb0ce4f48.
go-hass-agent  version
12:15AM INF go-hass-agent: v5.3.0
go-hass-agent  --debug
12:17AM DBG Debug logging enabled.
12:17AM DBG Setting language to [en-US].
12:17AM DBG Running UpgradeConfig.
12:17AM DBG Registration status is true
12:17AM DBG Running ValidateConfig.
12:17AM DBG Could not export secret. error="key hass.secret not set"
12:17AM DBG Could not find any script files.
12:17AM WRN Unsupported or unknown portal. App sensors will not run.
12:17AM WRN Unable to execute org.freedesktop.problems.GetProblems on org.freedesktop.problems (args: []) error="The name org.freedesktop.problems was not provided by any .service files"
panic: interface conversion: interface {} is nil, not string

goroutine 42 [running]:
github.com/joshuar/go-hass-agent/internal/linux.(*upowerBattery).marshalBatteryStateUpdate(0xc000013968, {0x1192fd0, 0xc000424270}, 0x9)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/batterySensor.go:95 +0x4f4
github.com/joshuar/go-hass-agent/internal/linux.BatteryUpdater({0x1192fd0?, 0xc000424270}, {0x118b1c0, 0xc0003f5320})
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/batterySensor.go:320 +0x1c5
github.com/joshuar/go-hass-agent/internal/agent.(*Agent).startWorkers.func1(0x0?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/agent/agent.go:305 +0x76
created by github.com/joshuar/go-hass-agent/internal/agent.(*Agent).startWorkers
	/home/runner/work/go-hass-agent/go-hass-agent/internal/agent/agent.go:303 +0x316

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser  chrome

**Additional context**
I am not great on linux, but I can try and muscle my way around. I did my best to read and understand the provided instructions. 
With that said I am human and may have missed a step. I actually missed that as I didn't see a gui even though I am running Ubuntu desktop. I may have also just read the terminal command and just ran it without looking at the gui. If you can walk me through re-install I will try the gui and see if that works.

**Comment by joshuar** [comment]
Hey there, I released [5.3.1](https://github.com/joshuar/go-hass-agent/releases/tag/v5.3.1) which hopefully fixes this issue for you.

**Comment by akentner** [comment]
I browsed through the files and found out, that you use the env `XDG_CURRENT_DESKTOP`

For any reason, with Ubuntu it says `ubuntu:GNOME`, not `GNOME`

**Comment by joshuar** [comment]
Hey @akentner I was able to verify this as well in an Ubuntu VM.  Weird! I've made https://github.com/joshuar/go-hass-agent/commit/e3b2606cdad6fa8f94712f8b9f19da8a5197f35f which will fix this and will be in the next release, coming very soon!

**Comment by joshuar** [comment]
Hey @akentner, [v6.0.1](https://github.com/joshuar/go-hass-agent/compare/v6.0.0...v6.0.1) has been released which should fix this issue. Can you give it a try when you get a chance and report back?

**Comment by Compukid** [comment]
> Hey there, I released [5.3.1](https://github.com/joshuar/go-hass-agent/releases/tag/v5.3.1) which hopefully fixes this issue for you.

OMG, Sorry I haven't had time to work on my laptop until now and I downloaded 6.0.3 and it is working great.

thank you so much.

**Comment by Compukid** [comment]
Oh, this is my first issue I opened on github. Do I close the issue since it is fixed???

**Comment by joshuar** [comment]
Nice, thanks for getting back to me and confirming it works! that's great to hear. I'll close this issue out as I think all the issues mentioned are now resolved :smile: :tada:
