### ISSUE TITLE
Would be cool to detect Zoom call status

### ISSUE THREAD

**Issue by geekpete** [joshuar/go-hass-agent#6]
**Is your feature request related to a problem? Please describe.**
Detect if the agent host is on a zoom call

**Describe the solution you'd like**

Using something like `xdotool` you can detect if a zoom meeting is current or not,etc.

```
xdotool search --class zoom
xdotool search --class zoom getwindowname 92274836
```
or some simple example:

```
#!/bin/bash

while true; do
  # search --sync waits for the window to show up.
  #if xdotool search --sync --name "Zoom Meeting ID:" > /dev/null; then
  if xdotool search --sync --name "Zoom Meeting" > /dev/null; then
    echo "In zoom :)"
  else
    echo "No zoom"
  fi
  sleep 1
done
```

Things you might use this status for:
- turn on the "On Air" light outside your home office door to let people know you're on a call
- dim/set lights a certain way for calls
- mute noisy things in your environment to avoid distractions in Zoom calls

**Comment by joshuar** [comment]
Hey @geekpete thanks for trying out go-hass-agent. Yeah, I've been mulling how I can get a better application name which might help ease making automations in Home Assistant when certain apps have focus or are running. 

In my primary use-case, with playing games on Steam, I just have to match on `steam_app_*` in the Active App sensor. I made a template binary sensor "Playing Games" which is true when the Active App matches the former. But I could imagine it would be nicer and more useful to have a human-friendly application name.

Does the "Active App" sensor work for you at the moment and what does it report when you have a Zoom window focused (likely need to look at the sensor state history in Home Assistant)?

**Comment by fhp** [comment]
Another way to solve this would be to allow custom scripts to be added to this tool.
These scripts then report their output as a certain sensor, using some refresh interval.

This is how https://github.com/LAB02-Research/HASS.Agent works, and this seems very powerful. Especially with the Linux command-line ecosystem.

**Comment by joshuar** [comment]
Hey @fhp I like that idea! I'll mull over how to implement it. Look out for this feature in an upcoming release ;)

**Comment by joshuar** [comment]
Hey @fhp, script sensors can now be created with release 5.2.0.  See the [docs](https://github.com/joshuar/go-hass-agent/blob/main/docs/scripts.md) for how to configure them.

This may also meet your feature request @geekpete? 

I am still thinking about how I can get the application name/title as a native sensor and there does seem to be some development in the major desktops towards exposing this in an easier way.

**Comment by fhp** [comment]
Awesome, thanks for your work. I surely will take a look!

**Comment by joshuar** [comment]
I'm going to close this issue out on the assumption that the script sensor feature can fulfil the original request. If it is missing functionality, or there is a bug in using the script sensor functionality, please open an issue to report. Thanks for trying out go-hass-agent!

**Comment by fhp** [comment]
Finally got around to setting this up on my laptop, and the scripts work great!

Added the webcam script from #71 and a variant of that script to detect if my laptop is docked (by checking if `lsusb | grep Dock` returns anything).

So now I know if I'm in a call, and if my laptop is in my office, and using the screen_locked property, if I am near my laptop :grinning: That's a good start for a lot of automations.

**Comment by joshuar** [comment]
Awesome! I'm so glad the agent is useful for you @fhp!
