### ISSUE TITLE
[BUG] MQTT settings does not accept value with format <IP>:<Port>

### ISSUE THREAD

**Issue by akentner** [joshuar/go-hass-agent#63]
**Describe the bug**
When I use a IP Address for MQTT Server settings in UI settings, the form say "string is invalid"

**To Reproduce**
1. Open App settings
2. Use any IP address with port e.g. "192.168.1.6:1883" as value for MQTT Server
3. Leave the field

**Expected behavior**
MQTT Server also accepts format `<IP>:<Port>`

**Screenshots**
![image](https://github.com/joshuar/go-hass-agent/assets/190932/c6d76d1b-953a-47b9-b72d-592d091e181c)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Chrome
 - Version: 6.0.1

**Comment by joshuar** [comment]
Hey @akentner, the MQTT settings don't currently do anything as I haven't added the code for MQTT functionality yet. I added the settings and then got sidetracked with other features and fixes :smile:  I'll fix it up when I add the MQTT code. For the moment, I'll remove it in the next version to avoid confusion.

I'll close this off but keep an eye out for a future major version with actual working MQTT functionality :tada:
