### ISSUE TITLE
[BUG] go-hass-agent pulls nabu casa config without consent or explanation, resulting in errors in installs where remote nabu casa is not enabled

### ISSUE THREAD

**Issue by clarjon1** [joshuar/go-hass-agent#66]
**Describe the bug**
During setup, go-hass-agent pulls what would be the nabu casa dashboard URL from configs. somehow. 

This results in a lot of errors as I have nabu casa remote control disabled, as I have my own WAF and forwarding setup in use, i just pay to support the project and for the cloud voice stuff. I don't want it attempting to use nabu casa as a result.

As such, I've been getting errors in logs about failing to send data to home assistant, even tho i had entered the URL manually to be the URL that is accessible both on my LAN and external to my LAN

I also don't see any thing in docs about how to prevent it from attempting to touch the nabu casa endpoints 

![image](https://github.com/joshuar/go-hass-agent/assets/627845/877e7ba3-a1c8-4237-a878-db2cb0eddea0)

**Comment by joshuar** [comment]
Hey @clarjon1, when the agent registers with Home Assistant, Home Assistant itself provides the URL in its response that should be used by the agent to connect to it. If Home Assistant is registered with Nabu Casa, it will return URLs that reference the Nabu Casa endpoint, as per the [development docs](https://developers.home-assistant.io/docs/api/native-app-integration/sending-data):

```
To summarize, here's how requests should be made:

    1. If you have a Cloudhook URL, use that until a request fails. When a request fails, go to step 2.
    2. If you have a remote UI URL, use that to construct a webhook URL: <remote_ui_url>/api/webhook/<webhook_id>. When a request fails, go to step 3.
    3. Construct a webhook URL using the instance URL provided during setup: <instance_url>/api/webhook/<webhook_id>.
```

The way I've interpreted the above in the agent is to generate the request URL once, after registration, using the above rules. This URL is then always used. 

I suppose another interpretation would be to use the above rules to try on **every** request. In your environment, that would likely work, as I'm guessing the generated “webhook URL” would be not blocked. It would however introduce a slight delay in sensor data appearing in Home Assistant (as it would try to send it twice and fail before using the webhook URL), though this might not be noticeable. 

I could probably also add an option to the agent registration to “use the URL provided explicitly for requests” which would override the above rules and default to generating a webhook URL with the URL provided at registration. This would be against recommendations but should work.

I can look into implementing the above two things:

- try each URL in turn on failure
- allow overriding the URL for requests at registration

Until I implement that functionality, I think you can work around this manually by editing the config file.

If you open `~/.config/com.github.joshuar.go-hass-agent-debug/go-hass-agent.toml` with a text editor, you can generate the webhook URL by taking note of the `host` and `webhookid` fields under the _hass_ section and replacing the `apiurl` field value with:

`<host>/api/webhook/<webhookid>`

Restart the agent and it should start sending data via the webhook URL (which I'm assuming is not blocked for you).

Let me know if this works!

**Comment by joshuar** [comment]
Hey @clarjon1 I finally implemented what I hope is what you've requested here in version [7.2.0](https://github.com/joshuar/go-hass-agent/releases/tag/v7.2.0). Now when registering, there is a new option, **"Ignore Returned URLs** highlighted in this screen shot:

![image](https://github.com/joshuar/go-hass-agent/assets/7401/ddd92244-2a4b-4f43-9d8a-ab7a5170d3d0)

If you select that when registering, the agent will ignore the Home Assistant suggestion as explained in https://github.com/joshuar/go-hass-agent/issues/66#issuecomment-1859317589 and use the server you entered/selected at registration.

The catch is I can't really test this myself as I don't have a Home Assistant cloud account. I'm relying on understanding the registration flow and my code to assume the right functionality. Would be very appreciative of testing if you can!

Also to note, this isn't retroactive for existing installs. You'd need to re-register the agent to select the new functionality. For an existing install, you can still manually get similar behaviour by editing the config file depending on the version: 

**_For versions <7.0.0_**, see [my comment](https://github.com/joshuar/go-hass-agent/issues/66#issuecomment-1859317589) for the needed config edits above. 

**_For versions 7.0.0 and above_**:

- Edit  `~/.config/go-hass-agent/preferences.toml`.
- Take note of the `registration.host` and `hass.webhookid` preferences.
- Replace the `hass.apiurl` value with `<host>/api/webhook/<webhookid>`.

Hope this works!

**Comment by clarjon1** [comment]
As far as I can tell, it seems to be working! Not seeing it complain about the nabu casa url being unreachable in logs, it did grab the nabu casa endpoint but it's not seeming to be in use

I did a config wipe to confirm this.

(and now it's seemingly lost the ability to track the battery charge level again oh no but that's gonna need a different issue lol.)

Thanks so much, and apologies for the delay in testing -- been *hectic* here.

**Comment by joshuar** [comment]
Nice! That is great to hear! Thank you for getting back to me and no need to apologise, understandable that other stuff takes priority :) 

Hmm, I will tinker with the battery code. I admit it needs some attention to make it more robust. I'll do some more work on it. Look out for changes in upcoming releases.

**Comment by joshuar** [comment]
I'm going to close this issue off as I believe we have fixed the root issue. If there is still a problem, please re-open and we can restart troubleshooting.

Thanks!
