### ISSUE TITLE
Proposal: Add capabilities to the hass agent to control some functions of the OS

### ISSUE THREAD

**Issue by jaynis** [joshuar/go-hass-agent#74]
Right now the go-hass-agent only collects metrics from the OS and registers them as sensors in HA. What I would find really useful would be some controls in HA to operate certain areas of the OS where the agent runs on. For example:

- Shutdown / Hibernate
- Lock screen
- Audio control 
 
I think the biggest challenge here would be implementing this in a generic way which works for all / most of the systems. Especially screen lock and audio control can be quite distribution / desktop environment specific. What of course could be done is adding the option to execute arbitrary commands on the system, but this however might pose a security risk because anyone who has access to the MQTT broker could take over the system. A further way would be to add the option to pre-configure certain commands in the go-hass-agent UI which can be triggered from HA.

Hard to say what the best way of solving this would be and I think first of all it would be good to know whether this functionality is wanted at all or if the agent should rather stay read-only :smiley: .

**Comment by joshuar** [comment]
Hey @jaynis thanks for trying out Go Hass Agent. In answer to your question, yes indeed to being able to control the device running the agent from Home Assistant.  

I have built another tool, [go-hass-anything](https://github.com/joshuar/go-hass-anything) that contains some packages that I intend to re-use in go-hass-agent to provide this ability. 

For the controls, I'd probably stick to relying on D-Bus/Systemd for the various commands. This would cover a lot of the popular distributions.

I need to clean up the go-hass-anything code a little to integrate it into the agent. So look out for this in an upcoming release!

**Comment by joshuar** [comment]
Hey @jaynis just as an update, I've released [v6.4.0](https://github.com/joshuar/go-hass-agent/releases/tag/v6.4.0) which contains preliminary MQTT support. [Instructions](https://github.com/joshuar/go-hass-agent/blob/main/docs/mqtt.md) for use. Some caveats:

- Only either user/pass authentication or no authentication.
- Only supports non-encrypted connection.
- Only shutdown/reboot, lock/unlock screen controls so far.

I intend to expand it to support more authentication options and encrypted connections if possible, and more controls.

**Comment by jaynis** [comment]
Hi @joshuar . Thank you for pinging me! I just tried it out and the integration with HA generally looks good. However, the screenlock only works for me immediately after I have unlocked my PC manually. If I wait a couple of seconds after the manual unlock, locking via go-hass-agent does not work anymore despite of the event being correctly dispatched (I can see this in the `dbus-monitor`). Do you have an idea what that could be?

What works for me consistently is activating the screenlock by triggering the screensaver via the following dbus command: 
`dbus-send --type=method_call --dest=org.cinnamon.ScreenSaver /org/cinnamon/ScreenSaver org.cinnamon.ScreenSaver.Lock string:""`

But unfortunately this is desktop environment specific (in my case [cinnamon](https://github.com/linuxmint/Cinnamon)).

**Comment by joshuar** [comment]
Hey @jaynis I'm going to close this issue off as I believe we've sorted out everything in the original request besides audio controls. I've opened a separate issue for those in #122. If there is something still outstanding regarding this issue though, please re-open and let me know. 

Thanks!
